#################
# WandB Params #
#################
project:
  desc: A project is a set of experiments you can compare together. Each project gets a dedicated dashboard page, and you can easily turn on and off different groups of runs to compare different model versions.
  value: "Visual_Acuity"


###################
# Training Params #
###################
epochs:
  desc: Number of epochs to train over
  value: 1
batch_size:
  desc: Size of each mini-batch
  value: 32


################
# Model Params #
################
optimizer:
  value: "adam"
weights:
  value: "imagenet"
metrics:
  value: "accuracy"
loss:
  value: "sparse_categorical_crossentropy"
activation:
  value: 'softmax'


##################
# Dataset Params #
##################
height:
  desc: height of images
  value: 400
width:
  desc: width of images
  value: 400
channels:
  desc: number of color channels
  value: 3
