################
# Arcus Paths  #
################
project_root:
  value: "/Users/brookeryan/Developer/BaldiLab/Visual-Acuity/"
numpy_data:
  value: "/Users/brookeryan/Developer/BaldiLab/Visual-Acuity/np_data/"


########
# Cuda #
########
cuda:
  value: False
